package com.innowise.carmicroservice.enums;

public enum ActionTypeEnum {
    GET_CARS_TYPE,
    GET_PAYMENTS_TYPE,
    GET_PRICES_TYPE,
    GET_RENTS_TYPE,
    GET_RESERVATIONS_TYPE,
    CREATE_CAR_TYPE,
    CREATE_PAYMENT_TYPE,
    CREATE_PRICE_TYPE,
    CREATE_RENT_TYPE,
    CREATE_RESERVATION_TYPE,
    UPDATE_CAR_TYPE,
    UPDATE_PAYMENT_TYPE,
    UPDATE_PRICE_TYPE,
    UPDATE_RENT_TYPE,
    UPDATE_RESERVATION_TYPE,
    DELETE_CAR_TYPE,
    DELETE_PAYMENT_TYPE,
    DELETE_PRICE_TYPE,
    DELETE_RENT_TYPE,
    DELETE_RESERVATION_TYPE
}
