/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class UserDetailsResponse extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4842610226760564787L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserDetailsResponse\",\"namespace\":\"avro\",\"fields\":[{\"name\":\"status\",\"type\":\"int\"},{\"name\":\"userDetails\",\"type\":{\"type\":\"record\",\"name\":\"UserDetails\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"username\",\"type\":\"string\"},{\"name\":\"password\",\"type\":\"string\"},{\"name\":\"enabled\",\"type\":\"boolean\"},{\"name\":\"accountNonExpired\",\"type\":\"boolean\"},{\"name\":\"credentialsNonExpired\",\"type\":\"boolean\"},{\"name\":\"accountNonLocked\",\"type\":\"boolean\"},{\"name\":\"authorities\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UserDetailsResponse> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UserDetailsResponse> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<UserDetailsResponse> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<UserDetailsResponse> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<UserDetailsResponse> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this UserDetailsResponse to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a UserDetailsResponse from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a UserDetailsResponse instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static UserDetailsResponse fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int status;
  private avro.UserDetails userDetails;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UserDetailsResponse() {}

  /**
   * All-args constructor.
   * @param status The new value for status
   * @param userDetails The new value for userDetails
   */
  public UserDetailsResponse(java.lang.Integer status, avro.UserDetails userDetails) {
    this.status = status;
    this.userDetails = userDetails;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return status;
    case 1: return userDetails;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: status = (java.lang.Integer)value$; break;
    case 1: userDetails = (avro.UserDetails)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public int getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(int value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'userDetails' field.
   * @return The value of the 'userDetails' field.
   */
  public avro.UserDetails getUserDetails() {
    return userDetails;
  }


  /**
   * Sets the value of the 'userDetails' field.
   * @param value the value to set.
   */
  public void setUserDetails(avro.UserDetails value) {
    this.userDetails = value;
  }

  /**
   * Creates a new UserDetailsResponse RecordBuilder.
   * @return A new UserDetailsResponse RecordBuilder
   */
  public static avro.UserDetailsResponse.Builder newBuilder() {
    return new avro.UserDetailsResponse.Builder();
  }

  /**
   * Creates a new UserDetailsResponse RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserDetailsResponse RecordBuilder
   */
  public static avro.UserDetailsResponse.Builder newBuilder(avro.UserDetailsResponse.Builder other) {
    if (other == null) {
      return new avro.UserDetailsResponse.Builder();
    } else {
      return new avro.UserDetailsResponse.Builder(other);
    }
  }

  /**
   * Creates a new UserDetailsResponse RecordBuilder by copying an existing UserDetailsResponse instance.
   * @param other The existing instance to copy.
   * @return A new UserDetailsResponse RecordBuilder
   */
  public static avro.UserDetailsResponse.Builder newBuilder(avro.UserDetailsResponse other) {
    if (other == null) {
      return new avro.UserDetailsResponse.Builder();
    } else {
      return new avro.UserDetailsResponse.Builder(other);
    }
  }

  /**
   * RecordBuilder for UserDetailsResponse instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserDetailsResponse>
    implements org.apache.avro.data.RecordBuilder<UserDetailsResponse> {

    private int status;
    private avro.UserDetails userDetails;
    private avro.UserDetails.Builder userDetailsBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(avro.UserDetailsResponse.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.status)) {
        this.status = data().deepCopy(fields()[0].schema(), other.status);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.userDetails)) {
        this.userDetails = data().deepCopy(fields()[1].schema(), other.userDetails);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (other.hasUserDetailsBuilder()) {
        this.userDetailsBuilder = avro.UserDetails.newBuilder(other.getUserDetailsBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing UserDetailsResponse instance
     * @param other The existing instance to copy.
     */
    private Builder(avro.UserDetailsResponse other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.status)) {
        this.status = data().deepCopy(fields()[0].schema(), other.status);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.userDetails)) {
        this.userDetails = data().deepCopy(fields()[1].schema(), other.userDetails);
        fieldSetFlags()[1] = true;
      }
      this.userDetailsBuilder = null;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public int getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public avro.UserDetailsResponse.Builder setStatus(int value) {
      validate(fields()[0], value);
      this.status = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public avro.UserDetailsResponse.Builder clearStatus() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'userDetails' field.
      * @return The value.
      */
    public avro.UserDetails getUserDetails() {
      return userDetails;
    }


    /**
      * Sets the value of the 'userDetails' field.
      * @param value The value of 'userDetails'.
      * @return This builder.
      */
    public avro.UserDetailsResponse.Builder setUserDetails(avro.UserDetails value) {
      validate(fields()[1], value);
      this.userDetailsBuilder = null;
      this.userDetails = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'userDetails' field has been set.
      * @return True if the 'userDetails' field has been set, false otherwise.
      */
    public boolean hasUserDetails() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'userDetails' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public avro.UserDetails.Builder getUserDetailsBuilder() {
      if (userDetailsBuilder == null) {
        if (hasUserDetails()) {
          setUserDetailsBuilder(avro.UserDetails.newBuilder(userDetails));
        } else {
          setUserDetailsBuilder(avro.UserDetails.newBuilder());
        }
      }
      return userDetailsBuilder;
    }

    /**
     * Sets the Builder instance for the 'userDetails' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public avro.UserDetailsResponse.Builder setUserDetailsBuilder(avro.UserDetails.Builder value) {
      clearUserDetails();
      userDetailsBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'userDetails' field has an active Builder instance
     * @return True if the 'userDetails' field has an active Builder instance
     */
    public boolean hasUserDetailsBuilder() {
      return userDetailsBuilder != null;
    }

    /**
      * Clears the value of the 'userDetails' field.
      * @return This builder.
      */
    public avro.UserDetailsResponse.Builder clearUserDetails() {
      userDetails = null;
      userDetailsBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UserDetailsResponse build() {
      try {
        UserDetailsResponse record = new UserDetailsResponse();
        record.status = fieldSetFlags()[0] ? this.status : (java.lang.Integer) defaultValue(fields()[0]);
        if (userDetailsBuilder != null) {
          try {
            record.userDetails = this.userDetailsBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("userDetails"));
            throw e;
          }
        } else {
          record.userDetails = fieldSetFlags()[1] ? this.userDetails : (avro.UserDetails) defaultValue(fields()[1]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UserDetailsResponse>
    WRITER$ = (org.apache.avro.io.DatumWriter<UserDetailsResponse>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UserDetailsResponse>
    READER$ = (org.apache.avro.io.DatumReader<UserDetailsResponse>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.status);

    this.userDetails.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.status = in.readInt();

      if (this.userDetails == null) {
        this.userDetails = new avro.UserDetails();
      }
      this.userDetails.customDecode(in);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.status = in.readInt();
          break;

        case 1:
          if (this.userDetails == null) {
            this.userDetails = new avro.UserDetails();
          }
          this.userDetails.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










